name: Vercel Preview Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches-ignore:
            - main

jobs:
    test-api:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      api/validate

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.18"

            - name: Build
              run: |
                  cd api/validate
                  go build -v

            - name: Test
              run: go test -v

    deploy-preview:
        needs: test-api
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
